# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'jaxwilko.hugo::lang.models.workflowresult.label'

# Model Form Field configuration
form: $/jaxwilko/hugo/models/workflowresult/fields.yaml

# Model Class name
modelClass: JaxWilko\Hugo\Models\WorkflowResult

# Default redirect location
defaultRedirect: jaxwilko/hugo/workflowresults

# Create page
create:
    title: backend::lang.form.create_title
    redirect: jaxwilko/hugo/workflowresults/update/:id
    redirectClose: jaxwilko/hugo/workflowresults

# Update page
update:
    title: backend::lang.form.update_title
    redirect: jaxwilko/hugo/workflowresults
    redirectClose: jaxwilko/hugo/workflowresults

# Preview page
preview:
    title: backend::lang.form.preview_title

formLayout: fancy
