# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'jaxwilko.hugo::lang.models.lighthousereport.label'

# Model Form Field configuration
form: $/jaxwilko/hugo/models/lighthousereport/fields.yaml

# Model Class name
modelClass: JaxWilko\Hugo\Models\LighthouseReport

# Default redirect location
defaultRedirect: jaxwilko/hugo/lighthousereports

# Create page
create:
    title: backend::lang.form.create_title
    redirect: jaxwilko/hugo/lighthousereports/update/:id
    redirectClose: jaxwilko/hugo/lighthousereports

# Update page
update:
    title: backend::lang.form.update_title
    redirect: jaxwilko/hugo/lighthousereports
    redirectClose: jaxwilko/hugo/lighthousereports

# Preview page
preview:
    title: backend::lang.form.preview_title
