tests:
    label: 'Tests'
    view:
        list: $/jaxwilko/hugo/controllers/test/columns.yaml
        toolbarButtons:
            create: "Create"
            delete: "Delete"
        recordsPerPage: 15
        showSearch: true
    manage:
        list: $/jaxwilko/hugo/controllers/test/columns.yaml
        form: $/jaxwilko/hugo/controllers/test/fields.yaml
        recordsPerPage: 15
        showSearch: true

scheduled:
    label: 'Scheduled'
    view:
        list: $/jaxwilko/hugo/models/groupschedule/columns.yaml
        toolbarButtons: []
        recordsPerPage: 15
    manage:
        list: $/jaxwilko/hugo/models/groupschedule/columns.yaml
        form: $/jaxwilko/hugo/models/groupschedule/fields.yaml
        recordsPerPage: 15

reports:
    label: 'Reports'
    view:
        list: $/jaxwilko/hugo/models/testreport/columns.yaml
        toolbarButtons: []
        recordsPerPage: 15
    manage:
        list: $/jaxwilko/hugo/models/testreport/columns.yaml
        form: $/jaxwilko/hugo/models/testreport/fields.yaml
        recordsPerPage: 15

results:
    label: 'Reports'
    view:
        list: $/jaxwilko/hugo/models/testresult/columns.yaml
        toolbarButtons: []
        recordsPerPage: 15
    manage:
        list: $/jaxwilko/hugo/models/testresult/columns.yaml
        form: $/jaxwilko/hugo/models/testresult/fields.yaml
        recordsPerPage: 15
