# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'jaxwilko.hugo::lang.models.site.label'

# Model Form Field configuration
form: $/jaxwilko/hugo/models/site/fields.yaml

# Model Class name
modelClass: JaxWilko\Hugo\Models\Site

# Default redirect location
defaultRedirect: jaxwilko/hugo/sites

# Create page
create:
    title: backend::lang.form.create_title
    redirect: jaxwilko/hugo/sites/update/:id
    redirectClose: jaxwilko/hugo/sites

# Update page
update:
    title: backend::lang.form.update_title
    redirect: jaxwilko/hugo/sites
    redirectClose: jaxwilko/hugo/sites

# Preview page
preview:
    title: backend::lang.form.preview_title
