actions:
    label: 'Actions'
    view:
        list: $/jaxwilko/hugo/controllers/actions/columns.yaml
        toolbarButtons:
            create: "Create"
            delete: "Delete"
        recordsPerPage: 15
        showSearch: true
    manage:
        list: $/jaxwilko/hugo/controllers/actions/columns.yaml
        form: $/jaxwilko/hugo/controllers/actions/fields.yaml
        recordsPerPage: 15
        showSearch: true

scheduled:
    label: 'Scheduled'
    view:
        list: $/jaxwilko/hugo/models/workflowschedule/columns.yaml
        toolbarButtons: []
        recordsPerPage: 15
        recordOnClick: void(0)
    manage:
        list: $/jaxwilko/hugo/models/workflowschedule/columns.yaml
        form: $/jaxwilko/hugo/models/workflowschedule/fields.yaml
        recordsPerPage: 15

results:
    label: 'Reports'
    view:
        list: $/jaxwilko/hugo/models/workflow/result-columns.yaml
        toolbarButtons: []
        recordsPerPage: 15
        recordUrl: /jaxwilko/hugo/workflowresults/update/:id
        filter:
            scopes:
                failed:
                    label: Hide Okay
                    type: checkbox
                    conditions: status <> 0

    manage:
        list: $/jaxwilko/hugo/models/workflowresult/columns.yaml
        form: $/jaxwilko/hugo/models/workflowresult/fields.yaml
        recordsPerPage: 15
